; Файл сопоставления символов с изображениями
; Формат: код_символа = относительный_путь_к_изображению
; Пути считаются относительно папки assets (или абсолютно, но лучше относительно assets)

[graphics_high]
0x0058 = images/tileChest.png
0x004B = images/tileKey.png
0x002E = images/tileGround.png
0x003E = images/tileDoorNext.png
0x003C = images/tileDoorPrev.png
0x003F = images/tileNPC.png
0x007C = images/tileBronzeSword.png
0x007D = images/tileIronArmor.png

; [gui]
; 0x0023 = gui/indicator.png
; 0x0024 = gui/button.png